# Generated by Django 5.0.5 on 2024-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
