# Generated by Django 5.0.5 on 2024-05-16 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_usuario_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
